language: perl
perl:
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
addons:
   postgresql: "9.3"
env:
  - DB_TESTING: 1
before_install:
   - "cpanm DBI"
   - "cpanm DBD::Pg"
   - "cpanm Try::Tiny"
   - "cpanm Memoize"
   - "cpanm Test::More"
   - "cpanm Test::Trap"
   - "cpanm Test::Exception"
   - "cpanm Devel::Cover::Report::Coveralls"
   - "cpanm Data::Dumper"
   - "cpanm Log::Log4perl"
   - "cpanm Locale::Maketext"
   - "cpanm DateTime"
   - "cpanm Locale::Maketext::Lexicon"
   - "cpanm MIME::Base64"
   - "cpanm Digest::MD5"
   - "cpanm HTML::Entities"
   - "cpanm Math::BigFloat"
   - "cpanm IO::File"
   - "cpanm IO::Scalar"
   - "cpanm Encode"
   - "cpanm Time::Local"
   - "cpanm Cwd"
   - "cpanm --force Class::Std"
   - "cpanm Config::Std"
   - "cpanm MIME::Lite"
   - "cpanm Template"
   - "cpanm Error"
   - "cpanm CGI::Simple"
   - "cpanm File::MimeInfo"
script:
   export RELEASE_TESTING=1 && yes n | perl Makefile.PL && PGUSER=postgres PGPASSWORD=test LSMB_TEST_DB=1 LSMB_NEW_DB=lsmb13installtest make test && cover -test -report coveralls
